# Generated by Django 2.1.1 on 2018-10-10 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0002_auto_20180908_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mensagemdecontato',
            options={'verbose_name': 'Mensagem de contato', 'verbose_name_plural': 'Mensagens de contato'},
        ),
        migrations.AlterField(
            model_name='mensagemdecontato',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_noticias.Categoria'),
        ),
    ]
