# Generated by Django 2.1 on 2018-10-31 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0003_auto_20181009_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoDeNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='app_noticias.Noticia')),
            ],
            options={
                'verbose_name': 'Foto de notícia',
                'verbose_name_plural': 'Fotos de notícias',
            },
        ),
    ]
